interface Env {
  DB: D1Database;
  CRABYARD_BOOTSTRAP_TOKEN?: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  GITHUB_ORG?: string;
  GITHUB_TOKEN?: string;
  CRABYARD_INTERACTIVE_PROVISION_URL?: string;
  CRABYARD_INTERACTIVE_PROVISION_TOKEN?: string;
  CRABYARD_RUNTIME_PROVISION_URL?: string;
  CRABYARD_RUNTIME_PROVISION_TOKEN?: string;
  CRABYARD_CLOUDFLARE_RUNNER_URL?: string;
  CRABYARD_CLOUDFLARE_RUNNER_TOKEN?: string;
  CRABYARD_CLOUDFLARE_RUNNER_INSTANCE_TYPE?: string;
  CRABYARD_CLOUDFLARE_RUNNER_WORKDIR?: string;
  CRABYARD_CLOUDFLARE_RUNNER_TTL_SECONDS?: string;
  CRABYARD_CLOUDFLARE_RUNNER_IDLE_SECONDS?: string;
  CRABYARD_CLAWFLEET_URL?: string;
  CRABYARD_CLAWFLEET_TOKEN?: string;
  CRABYARD_CLAWFLEET_PUBLIC_URL?: string;
}
