import { mkdir, readFile, rm, writeFile } from "node:fs/promises";

const appPath = new URL("../src/app.html", import.meta.url);
const specPath = new URL("../docs/spec.md", import.meta.url);
const logoPath = new URL("../src/assets/crabyard-logo.png", import.meta.url);
const ghosttyWebPath = new URL("../node_modules/ghostty-web/dist/ghostty-web.js", import.meta.url);
const ghosttyExternalPath = new URL(
  "../node_modules/ghostty-web/dist/__vite-browser-external-2447137e.js",
  import.meta.url,
);
const lucideIconNodesPath = new URL(
  "../node_modules/lucide-static/icon-nodes.json",
  import.meta.url,
);
const generatedPath = new URL("../src/generated.ts", import.meta.url);
const distRoot = new URL("../dist/", import.meta.url);
const distApp = new URL("../dist/app/", import.meta.url);
const distDocs = new URL("../dist/docs/", import.meta.url);

const [appHtmlSource, rawSpecMarkdown, logoBytes, ghosttyWebJs, ghosttyExternalJs, lucideIconJson] =
  await Promise.all([
    readFile(appPath, "utf8"),
    readFile(specPath, "utf8"),
    readFile(logoPath),
    readFile(ghosttyWebPath, "utf8"),
    readFile(ghosttyExternalPath, "utf8"),
    readFile(lucideIconNodesPath, "utf8"),
  ]);

const logoDataUrl = `data:image/png;base64,${logoBytes.toString("base64")}`;
const logoBase64 = logoBytes.toString("base64");
const lucideIconScript = buildLucideIconScript(JSON.parse(lucideIconJson));
const appHtml = appHtmlSource
  .replaceAll("__CRABYARD_LOGO__", logoDataUrl)
  .replace("__LUCIDE_ICONS__", lucideIconScript);
const specMarkdown = stripFrontmatter(rawSpecMarkdown);
const specHtml = renderSpecPage(specMarkdown);

await mkdir(new URL("../src/", import.meta.url), { recursive: true });
await writeFile(
  generatedPath,
  `// Generated by scripts/generate-assets.mjs. Do not edit by hand.\nexport const APP_HTML = ${JSON.stringify(appHtml)} as const;\nexport const LOGO_PNG_BASE64 = ${JSON.stringify(logoBase64)} as const;\nexport const SPEC_MARKDOWN = ${JSON.stringify(specMarkdown)} as const;\nexport const SPEC_HTML = ${JSON.stringify(specHtml)} as const;\nexport const GHOSTTY_WEB_JS = ${JSON.stringify(ghosttyWebJs)} as const;\nexport const GHOSTTY_BROWSER_EXTERNAL_JS = ${JSON.stringify(ghosttyExternalJs)} as const;\n`,
);

if (process.argv.includes("--static")) {
  await rm(distRoot, { recursive: true, force: true });
  await Promise.all([mkdir(distApp, { recursive: true }), mkdir(distDocs, { recursive: true })]);
  await writeFile(
    new URL("../dist/_redirects", import.meta.url),
    "/* https://crabyard.openclaw.ai/:splat 302\n",
  );
  await writeFile(new URL("../dist/index.html", import.meta.url), redirectHtml("/"));
  await writeFile(new URL("../dist/app/index.html", import.meta.url), redirectHtml("/app/"));
  await writeFile(new URL("../dist/docs/spec.md", import.meta.url), specMarkdown);
  await writeFile(new URL("../dist/crabyard-logo.png", import.meta.url), logoBytes);
  await writeFile(new URL("../dist/healthz", import.meta.url), "ok\n");
}

function redirectHtml(path) {
  const target = `https://crabyard.openclaw.ai${path}`;
  return `<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=${target}"><title>Crabyard.ai</title><a href="${target}">Crabyard.ai</a>`;
}

function buildLucideIconScript(iconNodes) {
  const names = ["book-open", "layout-grid", "moon", "settings", "sun", "terminal", "x"];
  const selected = Object.fromEntries(names.map((name) => [name, iconNodes[name]]));
  return `(() => {
  const icons = ${JSON.stringify(selected)};
  const attrs = 'xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';
  const attr = (value) => Object.entries(value).map(([key, raw]) => \`\${key}="\${String(raw).replaceAll('"', '&quot;')}"\`).join(" ");
  const node = ([tag, value]) => \`<\${tag} \${attr(value)}></\${tag}>\`;
  const svg = (name) => icons[name] ? \`<svg \${attrs} aria-hidden="true">\${icons[name].map(node).join("")}</svg>\` : "";
  globalThis.lucide = {
    createIcons() {
      document.querySelectorAll("i[data-lucide]").forEach((element) => {
        element.outerHTML = svg(element.dataset.lucide);
      });
    },
  };
})();`;
}

function stripFrontmatter(markdown) {
  return markdown.replace(/^---\n[\s\S]*?\n---\n+/, "");
}

function renderSpecPage(markdown) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Crabyard.ai Spec</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f6f3ee;
      --panel: #fffdf9;
      --text: #201f1c;
      --muted: #6d675f;
      --line: #dfd5c8;
      --accent: #a64834;
      --accent-soft: #f2d8cf;
      font-family: "Avenir Next", "Segoe UI", ui-sans-serif, system-ui, sans-serif;
    }
    * { box-sizing: border-box; }
    body { margin: 0; background: var(--bg); color: var(--text); line-height: 1.55; }
    header {
      position: sticky; top: 0; z-index: 1; border-bottom: 1px solid var(--line);
      background: color-mix(in srgb, var(--panel) 92%, transparent); backdrop-filter: blur(12px);
    }
    .bar { max-width: 1120px; margin: 0 auto; padding: 14px 24px; display: flex; align-items: center; justify-content: space-between; gap: 16px; }
    .brand { display: flex; align-items: center; gap: 10px; font-weight: 700; }
    .mark { width: 24px; height: 24px; border-radius: 7px; display: grid; place-items: center; color: var(--accent); background: var(--accent-soft); font-size: 13px; }
    nav { display: flex; gap: 14px; font-size: 14px; }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    main { max-width: 1120px; margin: 0 auto; padding: 36px 24px 64px; display: grid; grid-template-columns: minmax(0, 1fr) 260px; gap: 28px; }
    article { min-width: 0; padding: 34px 40px; border: 1px solid var(--line); border-radius: 8px; background: var(--panel); box-shadow: 0 1px 2px rgb(0 0 0 / 4%); }
    aside { align-self: start; position: sticky; top: 74px; padding: 18px; border: 1px solid var(--line); border-radius: 8px; background: var(--panel); color: var(--muted); font-size: 14px; }
    h1, h2, h3 { letter-spacing: 0; line-height: 1.2; margin: 1.5em 0 0.55em; }
    h1 { margin-top: 0; font-size: 34px; }
    h2 { padding-top: 10px; font-size: 23px; }
    h3 { font-size: 18px; }
    p, ul, ol, pre { margin: 0.7em 0; }
    ul, ol { padding-left: 1.35rem; }
    li + li { margin-top: 0.18rem; }
    code { border: 1px solid var(--line); border-radius: 5px; padding: 0.08rem 0.28rem; background: #fbf7f0; font-family: ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace; font-size: 0.92em; }
    pre { overflow: auto; padding: 15px 16px; border: 1px solid var(--line); border-radius: 8px; background: #fbf7f0; }
    pre code { border: 0; padding: 0; background: transparent; font-size: 13px; }
    @media (max-width: 900px) { main { grid-template-columns: 1fr; } aside { position: static; } article { padding: 26px 22px; } }
  </style>
</head>
<body>
  <header>
    <div class="bar">
      <div class="brand"><span class="mark">CY</span><span>Crabyard.ai</span></div>
      <nav><a href="/">App</a><a href="/docs/spec.md">Markdown</a><a href="https://github.com/openclaw/crabyard">GitHub</a></nav>
    </div>
  </header>
  <main>
    <article>${markdownToHtml(markdown)}</article>
    <aside><strong>Draft spec</strong><p>Cloud control plane for Codex sessions, cards, live attach, logs, and merge policy.</p></aside>
  </main>
</body>
</html>`;
}

function markdownToHtml(markdown) {
  const lines = markdown.split("\n");
  const html = [];
  let listTag;
  let inCode = false;
  let codeBuffer = [];

  for (const line of lines) {
    if (line.startsWith("```")) {
      if (inCode) {
        html.push(`<pre><code>${escapeHtml(codeBuffer.join("\n"))}</code></pre>`);
        codeBuffer = [];
        inCode = false;
      } else {
        closeList();
        inCode = true;
      }
      continue;
    }

    if (inCode) {
      codeBuffer.push(line);
      continue;
    }

    if (line.startsWith("# ")) {
      closeList();
      html.push(`<h1>${inline(line.slice(2))}</h1>`);
    } else if (line.startsWith("## ")) {
      closeList();
      html.push(`<h2>${inline(line.slice(3))}</h2>`);
    } else if (line.startsWith("### ")) {
      closeList();
      html.push(`<h3>${inline(line.slice(4))}</h3>`);
    } else if (line.startsWith("- ")) {
      openList("ul");
      html.push(`<li>${inline(line.slice(2))}</li>`);
    } else if (/^\d+\. /.test(line)) {
      openList("ol");
      html.push(`<li>${inline(line.replace(/^\d+\. /, ""))}</li>`);
    } else if (line.trim() === "") {
      closeList();
    } else {
      closeList();
      html.push(`<p>${inline(line)}</p>`);
    }
  }

  closeList();
  return html.join("\n");

  function openList(tag) {
    if (listTag === tag) return;
    closeList();
    html.push(`<${tag}>`);
    listTag = tag;
  }

  function closeList() {
    if (!listTag) return;
    html.push(`</${listTag}>`);
    listTag = undefined;
  }
}

function inline(value) {
  const escaped = escapeHtml(value);
  return escaped.replace(/`([^`]+)`/g, "<code>$1</code>");
}

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
